# Generated by Django 2.0.3 on 2018-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_calci'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
                ('created_date', models.DateField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
